services:
  db:
    image: postgres:17-alpine
    container_name: db-slothui
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - "./back/.env"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  redis:
    image: redis:7-alpine
    container_name: redis-slothui
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
  redisdata:
