FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
COPY front/package.json ./front/
COPY back/package.json ./back/
COPY back/nest-cli.json back/tsconfig.json back/tsconfig.build.json ./back/

RUN npm ci

WORKDIR /app/back
CMD ["npm", "run", "start:dev"]
